In [1]:
import pandas as pd
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.metrics import confusion_matrix,precision_score, accuracy_score, f1_score
dataset=pd.read_csv("/content/drive/MyDrive/dataset.csv")
"""print (dataset.shape)
dataset=dataset.sample(frac=1, replace=False)#shuffling dataset
print (dataset.shape)"""
labels=pd.DataFrame(dataset["label"])
dataset=dataset.drop("label",axis=1)

In [2]:
X_train, X_test, y_train, y_test = train_test_split(dataset, labels, test_size=0.3, random_state=42)


In [ ]:
import numpy as np
svm = SVC()

param_grid = {'C': [0.01, 1, 10], 'kernel': ['linear']}


"""
what thas that above ? check that


"""

grid_search = GridSearchCV(svm, param_grid, cv=5)

grid_search.fit(X_train, y_train['label'].ravel())


# Print the best hyperparameters and corresponding score
print("Best hyperparameters:", grid_search.best_params_)
print("Best score:", grid_search.best_score_)
kernel=grid_search.best_score_
c=grid_search.best_params_
best_params = grid_search.best_params_

In [3]:

X_train, X_test, y_train, y_test = train_test_split(dataset, labels, test_size=0.3, random_state=42)
#deg 5
classifier_svm_poly = SVC(kernel="rbf",C=23)#,degree=5)

# Fit the new classifier on the entire training set
classifier_svm_poly.fit(X_train, y_train['label'].ravel())
y_pred = classifier_svm_poly.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')

accuracy = accuracy_score(y_test, y_pred)

f1 = f1_score(y_test, y_pred, average='weighted')

print("Precision: ", precision)
print("Accuracy: ", accuracy)
print("F1 Score: ", f1)
print (cm)

Precision:  0.3703609819251848
Accuracy:  0.3538011695906433
F1 Score:  0.355741699547827
[[57 28  9 59 12  1]
 [ 9 59 21 14 44 18]
 [ 5 38 37  3 21 55]
 [22 25  8 92 21  1]
 [ 7 65 27 12 57 26]
 [ 5 36 31  9 31 61]]


In [4]:
for index, row in labels.iterrows():
    if "fake" in row["label"]:
        row["label"]="fake"
    else :
        row["label"]="real"

In [5]:
X_train, X_test, y_train, y_test = train_test_split(dataset, labels, test_size=0.3, random_state=42)
#deg 5
classifier_svm_poly = SVC(kernel="rbf",C=23)#,degree=5)

# Fit the new classifier on the entire training set
classifier_svm_poly.fit(X_train, y_train['label'].ravel())
y_pred = classifier_svm_poly.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')

accuracy = accuracy_score(y_test, y_pred)

f1 = f1_score(y_test, y_pred, average='weighted')

print("Precision: ", precision)
print("Accuracy: ", accuracy)
print("F1 Score: ", f1)
print (cm)

Precision:  0.5868895702634803
Accuracy:  0.5877192982456141
F1 Score:  0.5839558923215299
[[240 250]
 [173 363]]


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(dataset, labels, test_size=0.3, random_state=42)
#deg 5
classifier_svm_poly = SVC(kernel="linear",C=23)#,degree=5)

# Fit the new classifier on the entire training set
classifier_svm_poly.fit(X_train, y_train['label'].ravel())
y_pred = classifier_svm_poly.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')

accuracy = accuracy_score(y_test, y_pred)

f1 = f1_score(y_test, y_pred, average='weighted')

print("Precision: ", precision)
print("Accuracy: ", accuracy)
print("F1 Score: ", f1)
print (cm)