In [1]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,precision_score, accuracy_score, f1_score
from google.colab import drive
drive.mount('/content/drive')
dataset=pd.read_csv("/content/drive/MyDrive/dataset2.csv")
"""print (dataset.shape)
dataset=dataset.sample(frac=1, replace=False)#shuffling dataset
print (dataset.shape)"""
dataset = dataset.replace(float('-inf'), 0)


#dataset['magnitude_spectrum'] = dataset['magnitude_spectrum'].replace('-inf', dataset['magnitude_spectrum'].min())
labels=pd.DataFrame(dataset["label"])
dataset=dataset.drop("label",axis=1)


Mounted at /content/drive


In [ ]:
print (dataset)

      brightness  contrast     pattern  color_difference  edge_density  \
0      99.702134  0.416570  175.309872         24.562875     88.403188   
1      97.335692  0.623163  185.284147         57.123306     45.465668   
2      92.069242  0.619442  177.027386         62.602832     72.193555   
3     101.765685  0.612922  162.092529         63.141719     79.343781   
4      89.973461  0.622225  162.502445         61.500500     31.618202   
...          ...       ...         ...               ...           ...   
3412  110.619807  0.399236  200.791773          3.726273     36.949285   
3413  134.773247  0.375260  224.631836         22.195187     21.403370   
3414  115.248466  0.412123  217.522831          4.510632     40.676422   
3415  115.386924  0.413096  187.003233         19.096985     44.688034   
3416  112.719294  0.354879  214.505047          4.233398     29.153035   

      fractional_dimension           b           g           r        var_b  \
0             5.364788e-01   59.

In [2]:
from sklearn.naive_bayes import GaussianNB
X_train, X_test, y_train, y_test = train_test_split(dataset, labels, test_size=0.3, random_state=42)
nb = GaussianNB()
nb.fit(X_train, y_train['label'].ravel())
y_pred = nb.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')

accuracy = accuracy_score(y_test, y_pred)

f1 = f1_score(y_test, y_pred, average='weighted')

print("Precision: ", precision)
print("Accuracy: ", accuracy)
print("F1 Score: ", f1)
print (cm)

Precision:  0.34457049720026267
Accuracy:  0.2621832358674464
F1 Score:  0.20754962331666224
[[ 43 121   2   0   0   0]
 [ 18 145   2   0   0   0]
 [ 17 137   4   0   0   1]
 [ 52  61   1  36   5  14]
 [ 37  97   1  27   4  28]
 [ 30  86   0  16   4  37]]


In [3]:
from sklearn.naive_bayes import BernoulliNB,MultinomialNB
X_train, X_test, y_train, y_test = train_test_split(dataset, labels, test_size=0.3, random_state=42)
nb = BernoulliNB()
nb.fit(X_train, y_train['label'].ravel())
y_pred = nb.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')

accuracy = accuracy_score(y_test, y_pred)

f1 = f1_score(y_test, y_pred, average='weighted')

print("Precision: ", precision)
print("Accuracy: ", accuracy)
print("F1 Score: ", f1)
print (cm)

Precision:  0.17066937029760462
Accuracy:  0.31773879142300193
F1 Score:  0.2086920907868574
[[  0   0  71  92   0   3]
 [  0   0 126  30   0   9]
 [  0   0 121  35   0   3]
 [  0   0   8 136   0  25]
 [  0   0  30 119   0  45]
 [  0   0  18  86   0  69]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [4]:
for index, row in labels.iterrows():
    if "fake" in row["label"]:
        row["label"]="fake"
    else :
        row["label"]="real"


In [5]:
#for index, row in dataset.iterrows():
#    row['fractional_dimension']=row['fractional_dimension']*10

X_train, X_test, y_train, y_test = train_test_split(dataset, labels, test_size=0.3, random_state=42)


In [6]:
nb = GaussianNB()
nb.fit(X_train, y_train['label'].ravel())
y_pred = nb.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')

accuracy = accuracy_score(y_test, y_pred)

f1 = f1_score(y_test, y_pred, average='weighted')

print("Precision: ", precision)
print("Accuracy: ", accuracy)
print("F1 Score: ", f1)
print (cm)

Precision:  0.785941694272949
Accuracy:  0.6471734892787524
F1 Score:  0.6070096783044077
[[486   4]
 [358 178]]


In [7]:
nb = BernoulliNB(alpha=1.0, fit_prior=False)
nb.fit(X_train, y_train['label'].ravel())
y_pred = nb.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')

accuracy = accuracy_score(y_test, y_pred)

f1 = f1_score(y_test, y_pred, average='weighted')

print("Precision: ", precision)
print("Accuracy: ", accuracy)
print("F1 Score: ", f1)
print (cm)

Precision:  0.7906747008154442
Accuracy:  0.7777777777777778
F1 Score:  0.773709315375982
[[318 172]
 [ 56 480]]
