In [1]:
import pandas as pd
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.metrics import confusion_matrix,precision_score, accuracy_score, f1_score
from google.colab import drive
drive.mount('/content/drive')
dataset=pd.read_csv("/content/drive/MyDrive/dataset2.csv")
"""print (dataset.shape)
dataset=dataset.sample(frac=1, replace=False)#shuffling dataset
print (dataset.shape)"""
dataset = dataset.replace(float('-inf'), 0)


#dataset['magnitude_spectrum'] = dataset['magnitude_spectrum'].replace('-inf', dataset['magnitude_spectrum'].min())
labels=pd.DataFrame(dataset["label"])
dataset=dataset.drop("label",axis=1)


Mounted at /content/drive


In [2]:
X_train, X_test, y_train, y_test = train_test_split(dataset, labels, test_size=0.3, random_state=42)


In [ ]:
import numpy as np
svm = SVC()

param_grid = {'C': [0.01, 1, 2], 'kernel': ['linear']}


"""
what thas that above ? check that


"""

grid_search = GridSearchCV(svm, param_grid, cv=5)

grid_search.fit(X_train, y_train['label'].ravel())


# Print the best hyperparameters and corresponding score
print("Best hyperparameters:", grid_search.best_params_)
print("Best score:", grid_search.best_score_)
kernel=grid_search.best_score_
c=grid_search.best_params_
best_params = grid_search.best_params_

In [3]:

X_train, X_test, y_train, y_test = train_test_split(dataset, labels, test_size=0.3, random_state=42)
#deg 5
classifier_svm_poly = SVC(kernel="rbf",C=5)#,degree=5)

# Fit the new classifier on the entire training set
classifier_svm_poly.fit(X_train, y_train['label'].ravel())
y_pred = classifier_svm_poly.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')

accuracy = accuracy_score(y_test, y_pred)

f1 = f1_score(y_test, y_pred, average='weighted')

print("Precision: ", precision)
print("Accuracy: ", accuracy)
print("F1 Score: ", f1)
print (cm)

Precision:  0.23018735923849964
Accuracy:  0.246588693957115
F1 Score:  0.18081079358181532
[[ 11 128   0  26   1   0]
 [ 11 150   0   4   0   0]
 [  8 142   0   7   2   0]
 [ 27  55   0  55  18  14]
 [ 26  95   0  41  13  19]
 [ 13  79   0  44  13  24]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [4]:
for index, row in labels.iterrows():
    if "fake" in row["label"]:
        row["label"]="fake"
    else :
        row["label"]="real"

In [5]:
X_train, X_test, y_train, y_test = train_test_split(dataset, labels, test_size=0.3, random_state=42)
#deg 5
classifier_svm_poly = SVC(kernel="rbf",C=3)#,degree=5)

# Fit the new classifier on the entire training set
classifier_svm_poly.fit(X_train, y_train['label'].ravel())
y_pred = classifier_svm_poly.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')

accuracy = accuracy_score(y_test, y_pred)

f1 = f1_score(y_test, y_pred, average='weighted')

print("Precision: ", precision)
print("Accuracy: ", accuracy)
print("F1 Score: ", f1)
print (cm)

Precision:  0.7117034624416646
Accuracy:  0.6783625730994152
F1 Score:  0.6698349455241687
[[420  70]
 [260 276]]


In [9]:
X_train, X_test, y_train, y_test = train_test_split(dataset, labels, test_size=0.3, random_state=42)
#deg 5
classifier_svm_poly = SVC(kernel="sigmoid",C=3)#,degree=5)

# Fit the new classifier on the entire training set
classifier_svm_poly.fit(X_train, y_train['label'].ravel())
y_pred = classifier_svm_poly.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')

accuracy = accuracy_score(y_test, y_pred)

f1 = f1_score(y_test, y_pred, average='weighted')

print("Precision: ", precision)
print("Accuracy: ", accuracy)
print("F1 Score: ", f1)
print (cm)

Precision:  0.6889655659412435
Accuracy:  0.6890838206627681
F1 Score:  0.6890083178408448
[[328 162]
 [157 379]]


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(dataset, labels, test_size=0.3, random_state=42)
#deg 5
classifier_svm_poly = SVC(kernel="linear",C=3)#,degree=5)

# Fit the new classifier on the entire training set
classifier_svm_poly.fit(X_train, y_train['label'].ravel())
y_pred = classifier_svm_poly.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')

accuracy = accuracy_score(y_test, y_pred)

f1 = f1_score(y_test, y_pred, average='weighted')

print("Precision: ", precision)
print("Accuracy: ", accuracy)
print("F1 Score: ", f1)
print (cm)